# Generated by Django 3.2.7 on 2021-10-28 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
