# Generated by Django 3.2.7 on 2021-11-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0002_post_create_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
