# Generated by Django 3.2.7 on 2021-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0003_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
