# Generated by Django 3.2.7 on 2021-10-07 12:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_biodata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='Divorce',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='about_mehnot',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='about_owner',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='about_weakness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='address_of_wife',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='borka',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='business_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='children',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='children_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='class_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='dari',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='dini_qualification',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='divorced_houseband',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='education_after_married',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='foreign_houseband',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='graduate',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='graduate_pass_year',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='highest_education',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='hsc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='hsc_department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='hsc_pass_year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='hsc_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='job_after_married',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='job_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='mahram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='masna',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='monthly_income',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='muja',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='others_education',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='out_dress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='pant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='para',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='porda',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='ssc_department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='ssc_pass_year',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='ssc_result',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='varsity',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
