# Generated by Django 3.2.7 on 2021-10-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_biodata_publist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='publist',
            new_name='publish',
        ),
    ]
