# Generated by Django 3.2.7 on 2021-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_rename_publist_biodata_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='education_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
