# Generated by Django 3.2.7 on 2021-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0007_auto_20211008_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='aqida',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
