# Generated by Django 3.2.7 on 2021-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0008_biodata_aqida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='height',
            field=models.FloatField(),
        ),
    ]
