# Generated by Django 3.2.7 on 2021-10-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0009_alter_biodata_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='daora_hadith',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='daora_hadith_year',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='natiza',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='takhassur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='takhassur_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='why_not_education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
