# Generated by Django 3.2.7 on 2021-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0010_auto_20211016_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='partner_age',
            new_name='partner_age1',
        ),
        migrations.RenameField(
            model_name='biodata',
            old_name='partner_height',
            new_name='partner_age2',
        ),
        migrations.AddField(
            model_name='biodata',
            name='partner_height1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biodata',
            name='partner_height2',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
