# Generated by Django 3.2.7 on 2021-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0011_auto_20211017_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='daora_hadith_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
