# Generated by Django 3.2.7 on 2021-10-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0013_auto_20211023_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='birth_year',
            field=models.CharField(max_length=50),
        ),
    ]
