# Generated by Django 3.2.7 on 2021-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0015_auto_20211023_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='height',
            field=models.CharField(max_length=50),
        ),
    ]
