# Generated by Django 3.2.7 on 2021-10-26 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0016_alter_biodata_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='accept_request',
            field=models.ManyToManyField(blank=True, default=None, related_name='accept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biodata',
            name='get_request',
            field=models.ManyToManyField(blank=True, default=None, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
