# Generated by Django 3.2.7 on 2021-11-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0019_auto_20211031_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='joutuk',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
