# Generated by Django 3.2.7 on 2021-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0020_biodata_joutuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('suggested', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
