# Generated by Django 3.2.7 on 2021-11-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0021_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggested',
            name='percentage',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='suggested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested', to='biodata.biodata'),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bio', to='biodata.biodata'),
        ),
    ]
