# Generated by Django 3.2.7 on 2021-11-01 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0022_auto_20211101_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='books',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suggested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bio', to=settings.AUTH_USER_MODEL),
        ),
    ]
