# Generated by Django 3.2.7 on 2021-11-01 14:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0023_auto_20211101_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='books',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
