# Generated by Django 3.2.7 on 2021-11-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0024_alter_biodata_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='family',
            new_name='family_details',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='accept_request',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='get_request',
        ),
        migrations.AddField(
            model_name='biodata',
            name='bondha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_bio', models.BooleanField()),
                ('request_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
