# Generated by Django 3.2.7 on 2021-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0025_auto_20211104_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='accept_bio',
            field=models.BooleanField(default=False),
        ),
    ]
