# Generated by Django 3.2.7 on 2021-11-04 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0026_alter_request_accept_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='accept_bio',
            new_name='accept',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_bio',
        ),
        migrations.AddField(
            model_name='request',
            name='request_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_request_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
