# Generated by Django 3.2.7 on 2021-11-05 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0027_auto_20211104_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 15, 49, 18, 967057)),
        ),
    ]
