# Generated by Django 3.2.7 on 2021-11-05 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0028_biodata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 20, 54, 53, 571495)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('send', 'send'), ('accept', 'accept'), ('reject', 'reject'), ('cancel', 'cancel'), ('married', 'married')], default=None, max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 5, 20, 54, 53, 573495))),
                ('biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biodata.biodata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
