# Generated by Django 3.2.7 on 2021-11-05 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0029_auto_20211105_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 0, 18, 45, 530334)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('send', 'send Request'), ('accept', 'accept Request'), ('reject', 'reject Request'), ('cancel', 'cancel Request'), ('married', 'married Request')], default=None, max_length=50),
        ),
    ]
