# Generated by Django 3.2.7 on 2021-11-05 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0030_auto_20211106_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
