# Generated by Django 3.2.7 on 2021-11-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0031_alter_biodata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
