# Generated by Django 3.2.7 on 2021-11-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0033_alter_notification_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='details',
        ),
    ]
