# Generated by Django 3.2.7 on 2021-11-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0034_remove_notification_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.TextField(blank=True, default=None),
        ),
    ]
