# Generated by Django 3.2.7 on 2021-11-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0035_notification_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='biodata',
            new_name='sender',
        ),
    ]
