# Generated by Django 3.2.7 on 2021-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0037_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_seen',
            name='seentime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
