# Generated by Django 3.2.7 on 2021-11-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0039_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
