# Generated by Django 3.2.7 on 2021-11-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0040_request_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
