# Generated by Django 3.2.7 on 2021-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0041_uniqueuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='seen',
            field=models.ManyToManyField(to='biodata.UniqueUser'),
        ),
    ]
