# Generated by Django 3.2.7 on 2021-11-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0042_biodata_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accept',
        ),
        migrations.AddField(
            model_name='request',
            name='action',
            field=models.CharField(blank=True, choices=[('send', 'send Request'), ('accept', 'accept Request'), ('reject', 'reject Request'), ('cancel', 'cancel Request'), ('married', 'married Request')], default=None, max_length=50),
        ),
    ]
