# Generated by Django 3.2.7 on 2021-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0044_alter_request_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='action',
            field=models.CharField(blank=True, choices=[('send', 'send Request'), ('accept', 'accept Request'), ('reject', 'reject Request'), ('cancel', 'cancel Request'), ('married', 'married Request')], default='send', max_length=50, null=True),
        ),
    ]
