# Generated by Django 3.2.7 on 2021-11-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0045_alter_request_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
