# Generated by Django 3.2.7 on 2021-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0046_alter_biodata_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='para',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
