# Generated by Django 3.2.7 on 2021-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0047_auto_20211116_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='height',
            field=models.IntegerField(),
        ),
    ]
