# Generated by Django 3.2.7 on 2021-11-19 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0048_alter_biodata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='porda',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
