# Generated by Django 3.2.7 on 2021-11-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0049_alter_biodata_porda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='partner_financial_status',
            field=models.TextField(),
        ),
    ]
