# Generated by Django 3.2.7 on 2021-11-21 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0051_auto_20211121_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='divorced_houseband',
        ),
    ]
