# Generated by Django 3.2.7 on 2021-11-05 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata', '0027_auto_20211104_2228'),
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Favourite',
        ),
    ]
