# Generated by Django 3.2.7 on 2021-10-03 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
