# Generated by Django 3.2.7 on 2021-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masala', '0002_auto_20210929_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith', models.TextField()),
                ('reference', models.TextField()),
            ],
        ),
    ]
