# Generated by Django 3.2.7 on 2021-09-28 13:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
